<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="11.0.0-preview.1.26230.3" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LibraryBook.Application\LibraryBook.Application.csproj" />
      <ProjectReference Include="..\LibraryBook.Communication\LibraryBook.Communication.csproj" />
      <ProjectReference Include="..\LibraryBook.Exception\LibraryBook.Exception.csproj" />
      <ProjectReference Include="..\LibraryBook.Infrastructure\LibraryBook.Infrastructure.csproj" />
    </ItemGroup>

</Project>
